import Foundation
import XCTest
@testable import MurmurCore

/// The bytes the Android app (Kotlin :core) produces, which this implementation must reproduce or open.
/// Generated by core/src/test/kotlin/app/murmur/core/CrossPlatformVectorsTest.kt.
final class VectorsTests: XCTestCase {
    private var v: [String: Any] = [:]

    override func setUpWithError() throws {
        let url = try XCTUnwrap(Bundle.module.url(forResource: "vectors", withExtension: "json"))
        v = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
    }

    /// Real crypto only exists on Apple platforms (the Linux build uses stand-ins).
    private func requireRealCrypto() throws {
        #if !canImport(Darwin)
        throw XCTSkip("CryptoKit vectors need an Apple platform")
        #endif
    }

    private func dict(_ key: String) -> [String: Any] { v[key] as! [String: Any] }
    private func list(_ key: String) -> [[String: Any]] { v[key] as! [[String: Any]] }
    private func bytes(_ d: [String: Any], _ key: String) -> [UInt8] { [UInt8](hex: d[key] as! String) }

    private func identity(_ i: Int) throws -> Identity {
        let d = list("identities")[i]
        return try Identity.fromPrivateKeys(signing: bytes(d, "signingSeed"), agreement: bytes(d, "agreementPrivate"))
    }

    // MARK: no crypto needed (run everywhere)

    func testNicknameRules() {
        for c in list("nicknames") {
            XCTAssertEqual(Murmur.isValidNickname(c["nickname"] as! String), c["valid"] as! Bool, "nickname \(c["nickname"]!)")
        }
    }

    func testChannelNormalization() {
        for c in list("channelNames") {
            XCTAssertEqual(Channels.normalize(c["input"] as! String), c["normalized"] as? String, "channel \(c["input"]!)")
        }
    }

    func testFragmentsMatch() {
        let f = dict("fragments")
        let out = Fragmenter.fragment(bytes(f, "data"), chunkSize: f["chunkSize"] as! Int, streamId: UInt32(f["streamId"] as! Int))
        XCTAssertEqual(out.map(Hex.encode), f["fragments"] as! [String])
        let r = Reassembler(clock: VirtualTime())
        var whole: [UInt8]?
        for frag in out.reversed() { whole = r.accept(frag) ?? whole }
        XCTAssertEqual(whole, bytes(f, "data"))
    }

    func testContentEncodings() throws {
        for c in list("dmContent") {
            let content = DmContent(kind: DmKind(rawValue: c["kind"] as! Int)!, messageId: MessageId.fromHex(c["messageId"] as! String)!,
                                    senderAgreementKey: bytes(c, "key"), body: c["body"] as! String)
            XCTAssertEqual(Hex.encode(try content.encode()), c["hex"] as! String)
            XCTAssertEqual(DmContent.decode(bytes(c, "hex")), content)
        }
        for c in list("roomContent") {
            let content = RoomContent(kind: RoomKind(rawValue: c["kind"] as! Int)!, nickname: c["nickname"] as! String,
                                      target: (c["target"] as? String).flatMap(PacketId.fromHex), body: c["body"] as! String)
            XCTAssertEqual(Hex.encode(try content.encode()), c["hex"] as! String)
            XCTAssertEqual(RoomContent.decode(bytes(c, "hex")), content)
        }
        let invite = dict("invite")
        XCTAssertEqual(ChannelInvites.body(channel: invite["channel"] as! String, key: bytes(invite, "key")), invite["body"] as! String)
        XCTAssertEqual(ChannelInvites.parse(invite["body"] as! String)?.key, bytes(invite, "key"))
        let offer = dict("callOffer")
        XCTAssertEqual(CallSignal.offerBody(key: bytes(offer, "key")), offer["body"] as! String)
        XCTAssertEqual(CallSignal.parseOffer(offer["body"] as! String)?.key, bytes(offer, "key"))
    }

    func testPacketStructureRoundTrips() throws {
        for p in list("packets") {
            let raw = bytes(p, "hex")
            guard case let .ok(packet) = PacketCodec.decode(raw) else { return XCTFail("\(p["name"]!) didn't decode") }
            XCTAssertEqual(packet.payload.typeCode, p["type"] as! Int)
            XCTAssertEqual(packet.ttl, p["ttl"] as! Int)
            XCTAssertEqual(packet.packetId.toHex(), p["packetId"] as! String)
            XCTAssertEqual(packet.senderId.toHex(), p["senderId"] as! String)
            XCTAssertEqual(packet.recipientId.toHex(), p["recipientId"] as! String)
            XCTAssertEqual(packet.timestamp, (p["timestamp"] as! NSNumber).int64Value)
            // Re-encoding the decoded fields reproduces Kotlin's bytes exactly (all but the signature).
            let unsigned = try PacketCodec.unsignedBytes(senderId: packet.senderId, publicKey: packet.senderKey, payload: packet.payload,
                                                         recipientId: packet.recipientId, ttl: packet.ttl, packetId: packet.packetId,
                                                         timestamp: packet.timestamp)
            XCTAssertEqual(Hex.encode(unsigned), p["unsigned"] as! String, "\(p["name"]!)")
            XCTAssertEqual(packet.encode(), raw)
            switch packet.payload {
            case let .announce(nickname, emoji, color, _):
                XCTAssertEqual(nickname, p["nickname"] as? String)
                XCTAssertEqual(emoji, p["emoji"] as? String)
                XCTAssertEqual(color, p["colorIndex"] as? Int)
            case let .publicMessage(nickname, text):
                XCTAssertEqual(nickname, p["nickname"] as? String)
                XCTAssertEqual(text, p["text"] as? String)
            case let .room(channel, _, _):
                XCTAssertEqual(channel, p["channel"] as? String)
            case let .call(callId, seq, _):
                XCTAssertEqual(callId.toHex(), p["callId"] as? String)
                XCTAssertEqual(Int(seq), p["seq"] as? Int)
            default:
                break
            }
        }
    }

    // MARK: real crypto (Apple platforms)

    func testIdentitiesAndHashes() throws {
        try requireRealCrypto()
        for (i, d) in list("identities").enumerated() {
            let id = try identity(i)
            XCTAssertEqual(Hex.encode(id.signing.publicKey), d["signingPublic"] as! String)
            XCTAssertEqual(Hex.encode(id.agreement.publicKey), d["agreementPublic"] as! String)
            XCTAssertEqual(id.peerId.toHex(), d["peerId"] as! String)
        }
        for h in list("sha256") {
            XCTAssertEqual(Hex.encode(Sha256.hash(bytes(h, "input"))), h["output"] as! String)
        }
        let shared = try identity(0).agreement.agree(try identity(1).agreement.publicKey)
        XCTAssertEqual(shared.map(Hex.encode), v["x25519Shared"] as? String)
    }

    func testDmSealMatchesAndOpens() throws {
        try requireRealCrypto()
        let d = dict("dmSeal")
        let sealed = try XCTUnwrap(DmCrypto.seal(bytes(d, "plaintext"), recipientAgreementKey: bytes(d, "recipientAgreementPublic"),
                                                 aad: bytes(d, "aad"), random: ReplayRandom(bytes(d, "random"))))
        XCTAssertEqual(Hex.encode(sealed.ephemeralKey), d["ephemeralKey"] as! String)
        XCTAssertEqual(Hex.encode(sealed.nonce), d["nonce"] as! String)
        XCTAssertEqual(Hex.encode(sealed.ciphertext), d["ciphertext"] as! String)
        let opened = DmCrypto.open(sealed, recipient: try identity(1).agreement, aad: bytes(d, "aad"))
        XCTAssertEqual(opened, bytes(d, "plaintext"))
        XCTAssertNil(DmCrypto.open(sealed, recipient: try identity(0).agreement, aad: bytes(d, "aad")))
    }

    func testChannelKeyAndSeal() throws {
        try requireRealCrypto()
        let k = dict("channelKey")
        XCTAssertEqual(Hex.encode(ChannelCrypto.deriveKey(channel: k["channel"] as! String, password: k["password"] as! String,
                                                         iterations: k["iterations"] as! Int)), k["key"] as! String)
        let s = dict("channelSeal")
        let sealed = ChannelCrypto.seal(key: bytes(s, "key"), plaintext: bytes(s, "plaintext"), aad: bytes(s, "aad"), random: ReplayRandom(bytes(s, "random")))
        XCTAssertEqual(Hex.encode(sealed), s["sealed"] as! String)
        XCTAssertEqual(ChannelCrypto.open(key: bytes(s, "key"), sealed: bytes(s, "sealed"), aad: bytes(s, "aad")), bytes(s, "plaintext"))
    }

    func testCallSeal() throws {
        try requireRealCrypto()
        for c in list("callSeal") {
            let sealed = CallCrypto.seal(key: bytes(c, "key"), fromCaller: c["fromCaller"] as! Bool, seq: UInt32(c["seq"] as! Int),
                                         aad: bytes(c, "aad"), plaintext: bytes(c, "plaintext"))
            XCTAssertEqual(Hex.encode(sealed), c["sealed"] as! String)
        }
    }

    func testSafetyNumberAndPin() throws {
        try requireRealCrypto()
        let s = dict("safetyNumber")
        XCTAssertEqual(SafetyNumber.digits(bytes(s, "keyA"), bytes(s, "keyB")), s["digits"] as! String)
        XCTAssertEqual(SafetyNumber.digits(bytes(s, "keyB"), bytes(s, "keyA")), s["digits"] as! String)
        let p = dict("pin")
        XCTAssertEqual(Hex.encode(PinHasher.hash(pin: p["pin"] as! String, salt: bytes(p, "salt"), iterations: p["iterations"] as! Int)), p["hash"] as! String)
        XCTAssertTrue(PinHasher.verify(pin: p["pin"] as! String, salt: bytes(p, "salt"), expected: bytes(p, "hash")))
    }

    /// Android's signatures verify here, Android's DMs and channel messages open here, and packets this
    /// side signs verify (with the same signer-independent check Android uses).
    func testAndroidPacketsVerifyAndOpen() throws {
        try requireRealCrypto()
        let bob = try identity(1)
        let channelKey = bytes(dict("channelKey"), "key")
        for p in list("packets") {
            guard case let .ok(packet) = PacketCodec.decode(bytes(p, "hex")) else { return XCTFail() }
            XCTAssertEqual(PacketCodec.verify(packet), .ok, "\(p["name"]!)")
            XCTAssertEqual(PacketCodec.verify(packet.withTtl(2)), .ok, "ttl is outside the signature")
            var tampered = packet.encode()
            tampered[tampered.count - 70] ^= 1
            if case let .ok(t) = PacketCodec.decode(tampered) { XCTAssertNotEqual(PacketCodec.verify(t), .ok) }

            switch p["name"] as! String {
            case "private":
                let content = try XCTUnwrap(PrivateMessages.open(packet, me: bob))
                XCTAssertEqual(content.body, p["body"] as? String)
                XCTAssertEqual(content.messageId.toHex(), p["messageId"] as? String)
            case "roomEncrypted":
                guard case let .room(channel, encrypted, body) = packet.payload else { return XCTFail() }
                XCTAssertTrue(encrypted)
                let plain = try XCTUnwrap(ChannelCrypto.open(key: channelKey, sealed: body, aad: ChannelCrypto.aad(
                    packetId: packet.packetId.toBytes(), senderId: packet.senderId.toBytes(), timestamp: packet.timestamp, channel: channel)))
                XCTAssertEqual(RoomContent.decode(plain)?.body, p["body"] as? String)
            default:
                break
            }
        }
        // A packet signed here verifies.
        let mine = try PacketCodec.create(signing: bob.signing, payload: .publicMessage(nickname: "Bob", text: "from iPhone"),
                                          recipientId: .broadcast, ttl: 7, packetId: Id128(hi: 1, lo: 2), timestamp: baseTime)
        guard case let .ok(decoded) = PacketCodec.decode(mine.encode()) else { return XCTFail() }
        XCTAssertEqual(PacketCodec.verify(decoded), .ok)
    }
}
